#!/bin/bash

BASE=$(dirname "$0")
BASE=$(cd "$BASE"; pwd)

#
# setup bash
#
ln -sf $BASE/bash/bash_profile $HOME/.bash_profile
ln -sf $BASE/bash/bashrc $HOME/.bashrc

#
# setup zsh
#
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
ln -sf $BASE/zshrc $HOME/.zshrc


#
# setup vim
#
cd vim
VIMVER=$(vim --version | head -n1 | cut -d ' ' -f 5)
if [ "$VIMVER" != 7.3 ];
then
    ./force_dotfiles_reinstall
fi
curl http://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh

ln -sf $BASE/vim/vimrc $HOME/.vimrc
ln -sf $BASE/vim/vimrc.local $HOME/.vimrc.local

# ACK - grep alternative
mkdir -p $HOME/bin
curl http://beyondgrep.com/ack-2.10-single-file > $HOME/bin/ack && chmod 0755 $HOME/bin/ack

# Byobu
$BASE/byobu/byobu_install

# Gnuplot
ln -sf $BASE/gnuplot.2 $HOME/.gnuplot
