#!/bin/bash

# stop execution on any error
set -e

BASE=$(dirname "$0")
BASE=$(cd "$BASE"; pwd)

sudo yum install -y gcc g++ cmake python-devel ncurses-devel libXt-devel

cd "$BASE/vim"
wget -c ftp://ftp.vim.org/pub/vim/unix/vim-7.3.tar.bz2
tar xf vim-7.3.tar.bz2
cd vim73/src
./configure --with-features=huge --with-gnome --prefix=$HOME/vim73
make -j5
make install
cd "$BASE/vim"
rm -rf vim73
echo 'export PATH=$HOME/vim73/bin:$PATH' >>$HOME/.bashrc
echo 'export PATH=$HOME/vim73/bin:$PATH' >>$HOME/.zshrc

